databases:
  - name: cargogo
    databaseName: cargogo
    user: cargogo
    plan: free
    maxmemoryPolicy: noeviction

services:
  - type: web
    name: cargogo
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    plan: free
    maxmemoryPolicy: noeviction
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cargogo
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction

