databases:
  - name: cargogo
    databaseName: cargogo
    user: cargogo

services:
  - type: web
    name: cargogo
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cargogo
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
