default: &default
  adapter: postgresql
  encoding: unicode
  database: cargogo_backend_development
  pool: 5
  host: localhost
  username: postgres

development:
  <<: *default
  database: cargogo_backend_development
  username: postgres
  password: admin

test:
  <<: *default
  database: cargogo_backend_test
  username: postgres
  password: admin

production:
  <<: *default
  database: cargogo_backend_production
  username: cargogo_backend
  url: <%= ENV['DATABASE_URL'] %>
