default: &default
  adapter: postgresql
  encoding: unicode
  database: cargogo_backend_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres

development:
  <<: *default
  database: cargogo_backend_development
  username: postgres
  password: admin

test:
  <<: *default
  database: cargogo_backend_test
  username: postgres
  password: admin

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: cargogo_backend_production
  username: cargogo_backend

